apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: minio
spec:
  defaultInstallValues:
    - enabled: true
      resources: {}
  description: etcd is a strongly consistent, distributed key-value store that provides
    a reliable way to store data that needs to be accessed by a distributed system
    or cluster of machines.
  helm:
    chartLocationURL: file:///minio-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
    chartsPathInImage: /charts
    installValues: {}
    valuesMapping:
      jsonMap: {}
      valueMap: {}
  install:
    enabled: true
    resources: {}
  installable:
    autoInstall: true
  provider: community
  type: Helm
  version: 1.0.1
---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: document
    addon.kubeblocks.io/name: mongodb
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: mongodb
spec:
  defaultInstallValues:
    - enabled: true
  description: MongoDB is a document database designed for ease of application development
    and scaling.
  helm:
    chartLocationURL: file:///mongodb-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
  installable:
    autoInstall: true
  type: Helm

---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=1.0.0'
  labels:
    addon.kubeblocks.io/model: search-engine
    addon.kubeblocks.io/name: elasticsearch
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: elasticsearch
spec:
  defaultInstallValues:
    - enabled: true
  description: Elasticsearch is a distributed, RESTful search engine optimized for
    speed and relevance on production-scale workloads.
  helm:
    chartLocationURL: file:///elasticsearch-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
  installable:
    autoInstall: true
  type: Helm
---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=1.0.0'
  labels:
    addon.kubeblocks.io/model: message
    addon.kubeblocks.io/name: rabbitmq
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: rabbitmq
spec:
  defaultInstallValues:
    - enabled: true
  description: RabbitMQ is a reliable and mature messaging and streaming broker.
  helm:
    chartLocationURL: file:///rabbitmq-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
  installable:
    autoInstall: true
  type: Helm
---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: mariadb
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: mariadb
spec:
  defaultInstallValues:
    - enabled: true
  description: MariaDB is a high performance open source relational database management
    system that is widely used for web and application servers
  helm:
    chartLocationURL: file:///mariadb-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
  installable:
    autoInstall: true
  type: Helm
---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.7.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: mysql
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: mysql
spec:
  defaultInstallValues:
    - enabled: true
  description: MySQL is a widely used, open-source relational database management
    system (RDBMS)
  helm:
    chartLocationURL: file:///mysql-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext2
  installable:
    autoInstall: true
  type: Helm
---
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=1.0.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: clickhouse
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1
  name: clickhouse
spec:
  defaultInstallValues:
    - enabled: true
  description: ClickHouse is an open-source column-oriented OLAP database management
    system. Use it to boost your database performance while providing linear scalability
    and hardware efficiency.
  helm:
    chartLocationURL: file:///clickhouse-1.0.1.tgz
    chartsImage: beclab/kubeblock-addon-charts:v1.0.1-ext3
  installable:
    autoInstall: true
  type: Helm